name: Continuous integration

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build
      run: |
        ./mvnw clean package spring-boot:repackage
    - name: Save build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: target
        path: ./target
